#! /bin/sh



bspdir="$HOME/.config/bspwm"
polydir="$HOME/.config/bspwm/rices/$RICETHEME/polybar"

function launch() {
  local running
  running="$(pidof "$1")"
  [ "$running" ] && kill -9 $(pidof $1)
  eval "$* &"
}

function WallChanger() {
	local wallimage
	wallimage="$(shuf -en1 ~/.config/bspwm/rices/$RICETHEME/*.webp)"
	feh --no-fehbg --bg-fill $wallimage
}

function killeww() {
  if [[ `pidof eww` ]]; then 
		pkill eww
  fi
}

function ResetTermite() {
  if [[ `pidof termite` ]]; then 
		killall -USR1 termite
  fi
}

function ReloadTermite() {
  if [ -f "$HOME/.config/termite/config" ]; then
		cat $HOME/.config/bspwm/rices/$RICETHEME/termiterc > $HOME/.config/termite/config
		ResetTermite
  else
		mkdir -p $HOME/.config/termite/ && touch $HOME/.config/termite/config
		cat $HOME/.config/bspwm/rices/$RICETHEME/termiterc > $HOME/.config/termite/config
		ResetTermite
  fi
}

function SetBspwmConf() {
	bspc config border_width "$1"
	bspc config top_padding "$2"
	bspc config bottom_padding "$3"
	bspc config normal_border_color "$4" 
	bspc config active_border_color "$5"
	bspc config focused_border_color "$6"
	bspc config presel_feedback_color "$7"
	bspc config left_padding "$8"
	bspc config right_padding "$9"
}

function SetGirlFriendRice() {
	
	case $RICETHEME in
	
		theme6)
		
		  SetBspwmConf 0 60 5 "#202132" "#202132" "#202132" "#070219" 5 5
		  		  
		  killeww
		  launch polybar -q emi-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
			
		theme0)
		
		  SetBspwmConf 0 60 5 "#4C3A6D" "#4C3A6D" "#785DA5" "#070219" 5 5
		  
		  killeww
		  launch polybar -q main -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		    

		  
		theme5)
		
		  SetBspwmConf 0 5 45 "#333a48" "#333a48" "#333a48" "#4f4f5b" 5 5
		  
		  killeww
		  launch polybar -q isa-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		theme7)
		
		  SetBspwmConf 0 45 5 "#4C3A6D" "#4C3A6D" "#785DA5" "#070219" 5 5
		  
		  killeww
		  launch polybar -q cyn-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		theme2)
		
		  SetBspwmConf 0 45 5 "#bdae93" "#bdae93" "#bdae93" "#4f4f5b" 5 5

		  killeww
		  launch polybar -q cata-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		
		theme4)
		
		  SetBspwmConf 0 42 40 "#4c566a" "#4c566a" "#4c566a" "#4f4f5b" 5 5	

		  killeww
		  launch polybar -q mel-bar -c ${polydir}/config.ini
		  polybar -q mel2-bar -c ${polydir}/config.ini & disown
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		theme3)
		
		  SetBspwmConf 0 60 5 "#bdae93" "#bdae93" "#bdae93" "#4f4f5b" 5 5
		  
		  killeww
		  launch polybar -q pam1 -c ${polydir}/config.ini
		  polybar -q pam2 -c ${polydir}/config.ini & disown
		  polybar -q pam3 -c ${polydir}/config.ini & disown
		  polybar -q pam4 -c ${polydir}/config.ini & disown
		  polybar -q pam5 -c ${polydir}/config.ini & disown
		  polybar -q pam6 -c ${polydir}/config.ini & disown
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		theme1)
		
		  SetBspwmConf 0 10 60 "#bdae93" "#bdae93" "#bdae93" "#4f4f5b" 5 5
		  
		  killeww
		  launch polybar -q cristina-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  

		  

		  
	esac		
}

ReloadTermite

function AutoStartApps() {
	
	launch sxhkd -c ${bspdir}/sxhkdrc &
	launch picom --config ${bspdir}/rices/$RICETHEME/picom.conf &
	launch /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
	WallChanger
	#nitrogen --restore &
	xsetroot -cursor_name left_ptr
	
}
